#配置数据源
spring:
  application:
    name: yshop-system
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dynamic-site?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
  session:
    store-type: none
yqm:
  security:
    browse:
      login-url: /authentication/login # 登录入口
      login-page: /authentication/require # 当需要身份认证的时候，跳转到这里
      username-parameter: username # 登录提交表单的 账号 参数名
      password-parameter: password # 登录提交表单的 密码 参数名
    code: # 图形验证码 宽 高 大小 有效期
      width: 67
      height: 23
      length: 4
      expireIn: 60
